# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from selenium import webdriver
import time

from PyQt5 import QtCore, QtGui, QtWidgets


def login():
    brave = "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"

    web = webdriver.Chrome()
    web.get("http://172.16.1.1:8090/httpclient.html?u=http://www.gstatic.com/generate_204")

    time.sleep(2)
    user = 'btech1040120'
    user_path = web.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[1]/div[1]/input[1]")
    user_path.send_keys(user)

    passwd = '17082001'
    passwd_path = web.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[1]/div[1]/input[2]')
    passwd_path.send_keys(passwd)

    login = web.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[3]")
    login.click()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 265)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 351, 271))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.790614, y2:0.511, stop:0 rgba(71, 118, 230, 255), stop:1 rgba(142, 84, 233, 255));}")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget,clicked=lambda:self.press())
        self.pushButton.setGeometry(QtCore.QRect(70, 100, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color:#ffbfcf;\n"
"border-radius:20px;\n"
"border:2px solid #fff;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #fff;\n"
"  color: #514A9D;\n"
"   cursor: pointer;\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login BIT"))
        self.pushButton.setText(_translate("MainWindow", "LOGIN"))


    def press(self):
        login()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
